### ISSUE TITLE
running tests on checked out master does not work

### ISSUE THREAD

**Issue by jrochkind** [projectblacklight/blacklight_advanced_search#38]
I check out current master at 03f8af487ab. 

I run `bundle install`, then `bundle exec rake`, to try to run tests. 

It looks like it's doing some things to download and install a jetty. Then I get:

~~~ruby
DEPRECATION WARNING: RSolr should be in your gemfile. Blacklight 6.0 will not load rsolr by default. (called from <module:Blacklight> at /Users/jrochkind/.gem/ruby/1.9.3/gems/blacklight-5.13.0/lib/blacklight/solr_repository.rb:2)
DEPRECATION WARNING: Your application is missing the SearchBuilder. Have you run `rails generate blacklight:search_builder`? Falling back to Blacklight::Solr::SearchBuilder. (called from locate_search_builder_class at /Users/jrochkind/.gem/ruby/1.9.3/gems/blacklight-5.13.0/lib/blacklight/configuration.rb:225)
/Users/jrochkind/.gem/ruby/1.9.3/gems/blacklight-5.13.0/lib/blacklight.rb:97:in `blacklight_yml': You are missing a configuration file: /Users/jrochkind/code/blacklight_advanced_search/spec/internal/config/blacklight.yml. Have you run "rails generate blacklight:install"? (RuntimeError)
	from /Users/jrochkind/.gem/ruby/1.9.3/gems/blacklight-5.13.0/lib/blacklight.rb:82:in `connection_config'
	from /Users/jrochkind/.gem/ruby/1.9.3/gems/blacklight-5.13.0/lib/blacklight/configuration.rb:217:in `connection_config'
	from /Users/jrochkind/.gem/ruby/1.9.3/gems/blacklight-5.13.0/lib/blacklight/utils.rb:37:in `[]'
# ...
DEPRECATION WARNING: RSolr should be in your gemfile. Blacklight 6.0 will not load rsolr by default. (called from <module:Blacklight> at /Users/jrochkind/.gem/ruby/1.9.3/gems/blacklight-5.13.0/lib/blacklight/solr_repository.rb:2)
DEPRECATION WARNING: Your application is missing the SearchBuilder. Have you run `rails generate blacklight:search_builder`? Falling back to Blacklight::Solr::SearchBuilder. (called from locate_search_builder_class at /Users/jrochkind/.gem/ruby/1.9.3/gems/blacklight-5.13.0/lib/blacklight/configuration.rb:225)
rake aborted!
You are missing a configuration file: /Users/jrochkind/code/blacklight_advanced_search/spec/internal/config/blacklight.yml. Have you run "rails generate blacklight:install"?
/Users/jrochkind/.gem/ruby/1.9.3/gems/blacklight-5.13.0/lib/blacklight.rb:97:in `blacklight_yml'
/Users/jrochkind/.gem/ruby/1.9.3/gems/blacklight-5.13.0/lib/blacklight.rb:82:in `connection_config'
/Users/jrochkind/.gem/ruby/1.9.3/gems/blacklight-5.13.0/lib/blacklight/configuration.rb:217:in `connection_config'
# ...
~~~

Then more `bundle install` output, so I'm not sure if that stopped it or not? Then a bunch of solr/jetty log lines. Then another set of deprecations, followed by:

~~~
NameError: uninitialized constant SolrDocument
/Users/jrochkind/.gem/ruby/1.9.3/gems/blacklight-5.13.0/lib/blacklight/configuration.rb:186:in `document_model'
/Users/jrochkind/.gem/ruby/1.9.3/gems/blacklight-5.13.0/lib/blacklight/utils.rb:37:in `[]'
/Users/jrochkind/.gem/ruby/1.9.3/gems/blacklight-5.13.0/lib/blacklight/configuration.rb:181:in `block in initialize_default_values!'
/Users/jrochkind/.gem/ruby/1.9.3/gems/blacklight-5.13.0/lib/blacklight/configuration.rb:180:in `each'
/Users/jrochkind/.gem/ruby/1.9.3/gems/blacklight-5.13.0/lib/blacklight/configuration.rb:180:in `initialize_default_values!'
/Users/jrochkind/.gem/ruby/1.9.3/gems/blacklight-5.13.0/lib/blacklight/configuration.rb:172:in `initialize'
/Users/jrochkind/.gem/ruby/1.9.3/gems/blacklight-5.13.0/lib/blacklight.rb:72:in `new'
~~~

That one seems to finally kill it with, a `Error running fixtures`.  Specs were not run. 

Is there a way to run specs locally in current master?

**Comment by awead** [comment]
What version of Blacklight is it pulling? Do you get the same problem if you're using 5.12, or 5.11? I can't remember which version last worked for me.

**Comment by atz** [comment]
We've since switched to `solr_wrapper` and 2.2+ versions of Ruby, so I'm going to close this.  Please reopen if you get the same or similar issues on the contemporary stack.
